<a href="https://colab.research.google.com/github/KritikaShami/MachineLearning/blob/main/K_fold_xvalidation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from sklearn.datasets import load_wine
import matplotlib.pyplot as plt
wine = load_wine()

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(wine.data,wine.target,test_size=0.3)

In [ ]:
print(X_train)

[[1.208e+01 1.130e+00 2.510e+00 ... 1.310e+00 2.720e+00 6.300e+02]
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.373e+01 4.360e+00 2.260e+00 ... 7.800e-01 1.750e+00 5.200e+02]
 ...
 [1.388e+01 1.890e+00 2.590e+00 ... 8.800e-01 3.560e+00 1.095e+03]
 [1.267e+01 9.800e-01 2.240e+00 ... 1.230e+00 3.160e+00 4.500e+02]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]]


In [ ]:
wine.target[[10,80,140]]

array([0, 1, 2])

In [ ]:
list(wine.target_names)

['class_0', 'class_1', 'class_2']

**Training dataset using 3 different classifiers**

**Decision Tree Classifier**

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)
dt.score(X_test, y_test)

0.9074074074074074

**Gaussian Naive Bayes**

In [ ]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)
gnb.score(X_test, y_test)


0.9814814814814815

**Multinomial Naive Bayes**

In [ ]:
from sklearn.naive_bayes import MultinomialNB
mnb = MultinomialNB()
mnb.fit(X_train, y_train)
mnb.score(X_test, y_test)

0.8148148148148148

**K-fold crosss-validation**

In [ ]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [ ]:
for train_index, test_index in kf.split(wine.data,wine.target):
    print(train_index, test_index)

[ 60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95
  96  97  98  99 100 101 102 103 104 105 106 107 108 109 110 111 112 113
 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131
 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149
 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167
 168 169 170 171 172 173 174 175 176 177] [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59 119 120 121 122 123 124 125 126 127 128 129 130
 131 132 133 134 135 136 137 138 139 140 141

In [ ]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [ ]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_dt = []
scores_gnb = []
scores_mnb = []

for train_index, test_index in folds.split(wine.data,wine.target):
    X_train, X_test, y_train, y_test = wine.data[train_index], wine.data[test_index], \
                                       wine.target[train_index], wine.target[test_index]
    scores_dt.append(get_score(DecisionTreeClassifier(), X_train, X_test, y_train, y_test))  
    scores_gnb.append(get_score(GaussianNB(), X_train, X_test, y_train, y_test))
    scores_mnb.append(get_score(MultinomialNB(), X_train, X_test, y_train, y_test))

In [ ]:
scores_dt

[0.9, 0.8305084745762712, 0.9152542372881356]

In [ ]:
scores_gnb

[0.95, 0.9661016949152542, 0.9661016949152542]

In [ ]:
scores_mnb

[0.7166666666666667, 0.8135593220338984, 0.9661016949152542]

**Cross-Validation**

In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
cross_val_score(DecisionTreeClassifier(), wine.data, wine.target,cv=3)

array([0.95      , 0.83050847, 0.93220339])

In [ ]:
cross_val_score(GaussianNB(), wine.data, wine.target,cv=3)

array([0.95      , 0.96610169, 0.96610169])

In [ ]:
cross_val_score(MultinomialNB(), wine.data, wine.target,cv=3)

array([0.71666667, 0.81355932, 0.96610169])

**Parameter tuning using k-fold**

In [ ]:
scores1 = cross_val_score(DecisionTreeClassifier(),wine.data, wine.target, cv=10)
np.average(scores1)

0.8594771241830067

In [ ]:
scores2 = cross_val_score(GaussianNB(),wine.data, wine.target, cv=10)
np.average(scores2)

0.9777777777777779

In [ ]:
scores3 = cross_val_score(MultinomialNB(),wine.data, wine.target, cv=10)
np.average(scores3)

0.8496732026143791