<a href="https://colab.research.google.com/github/KritikaShami/MachineLearning/blob/main/MultivariateLR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Predicting movie rating using Multinomial Naive Bayes

In [ ]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.linear_model import LinearRegression

In [ ]:
df = pd.read_csv('MovieData2.csv')
df

Viewers  Rating  Age  Overall_Rating
0      5000     5.0   20             4.0
1      4500     4.5   25             4.0
2      4000     4.0   40             5.0
3      4200     4.0   21             4.0
4      3400     3.0   12             2.0
5      2000     2.0   28             3.5
6      4300     NaN   45             4.2
7      3500     3.5   21             3.5
8      5000     5.0   55             2.5
9      4300     4.0    8             4.0
10     2500     NaN   14             1.0
11     3100     3.0   32             4.0
12     2700     2.5   12             3.5
13     4000     4.0   26             5.0

In [ ]:
df.Rating.median()

4.0

In [ ]:
df.Rating = df.Rating.fillna(df.Rating.median())
df

Viewers  Rating  Age  Overall_Rating
0      5000     5.0   20             4.0
1      4500     4.5   25             4.0
2      4000     4.0   40             5.0
3      4200     4.0   21             4.0
4      3400     3.0   12             2.0
5      2000     2.0   28             3.5
6      4300     4.0   45             4.2
7      3500     3.5   21             3.5
8      5000     5.0   55             2.5
9      4300     4.0    8             4.0
10     2500     4.0   14             1.0
11     3100     3.0   32             4.0
12     2700     2.5   12             3.5
13     4000     4.0   26             5.0

In [ ]:
reg = linear_model.LinearRegression()
reg.fit(df.drop('Overall_Rating',axis='columns'),df.Overall_Rating)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
reg.coef_

array([ 0.00138173, -1.21175984,  0.00978351])

In [ ]:
reg.intercept_

2.697456238286422

Find overall rating with 3000 viewers, social media rating:3 and age=40

In [ ]:
reg.predict([[3000, 3, 40]])

array([3.59870138])

Find overall rating with 2500 viewers, social media rating:4 and age=5

In [ ]:
reg.predict([[2500, 4, 5]])

array([1.35365462])

In [ ]:
df

Viewers  Rating  Age  Overall_Rating
0      5000     5.0   20             4.0
1      4500     4.5   25             4.0
2      4000     4.0   40             5.0
3      4200     4.0   21             4.0
4      3400     3.0   12             2.0
5      2000     2.0   28             3.5
6      4300     4.0   45             4.2
7      3500     3.5   21             3.5
8      5000     5.0   55             2.5
9      4300     4.0    8             4.0
10     2500     4.0   14             1.0
11     3100     3.0   32             4.0
12     2700     2.5   12             3.5
13     4000     4.0   26             5.0

In [ ]:
df = df.drop('Overall_Rating',axis='columns')

In [ ]:
test = list(df)

In [ ]:
print(test)

[[5000.0, 5.0, 20.0], [4500.0, 4.5, 25.0], [4000.0, 4.0, 40.0], [4200.0, 4.0, 21.0], [3400.0, 3.0, 12.0], [2000.0, 2.0, 28.0], [4300.0, 4.0, 45.0], [3500.0, 3.5, 21.0], [5000.0, 5.0, 55.0], [4300.0, 4.0, 8.0], [2500.0, 4.0, 14.0], [3100.0, 3.0, 32.0], [2700.0, 2.5, 12.0], [4000.0, 4.0, 26.0]]


In [ ]:
test = list()
for i in range(df.shape[0]):
  test.append(list(df.iloc[i]))  


In [ ]:
pred = list()
for i in test:
  pred.append(reg.predict([i]))

In [ ]:
pred[2][0]

3.768669610391043

In [ ]:
print(pred)

[array([3.74296762]), array([3.70690106]), array([3.76866961]), array([3.85912851]), array([3.8774543]), array([3.31133101]), array([4.23210559]), array([3.49779878]), array([4.08539051]), array([3.87011568]), array([1.44170622]), array([3.6586061]), array([3.51612457]), array([3.63170045])]


In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
plt.figure()
plt.scatter(x=list(range(0, 47)),y= y, color='blue')         
plt.scatter(x=list(range(0, 47)), y=y_hat, color='red')
plt.show()

NameError: ignored

<Figure size 432x288 with 0 Axes>